development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:ae3cc88430fd83bd7578e294d8b0b138@spinyfin.redistogo.com:10122/
    # <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: GRPBALL_production
